GET https://webapi1231.herokuapp.com/WeatherForecast

###
GET https://localhost:5001/api/TodoItems

###
POST https://localhost:5001/api/TodoItems
Content-Type: application/json

{
    "Id":1
    ,"Name":"測試者"
    ,"IsComplete":false
}

###
@hostname = webapibydb.herokuapp.com
GET https://{{hostname}}/api/TodoItems

###
POST https://{{hostname}}/api/TodoItems
Content-Type: application/json

{
    "Id":1
    ,"Name":"測試者"
    ,"IsComplete":false
}
